spring:
  application:
    name: kafkarator

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

logging:
  level:
    no.fintlabs: debug

fint:
  aiven:
    token:
    base-url: https://api.aiven.io/v1
    project: fintlabs
    service:
    kafka-bootstrap-servers:
    certificate-rotation-threshold: 30d
