kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kafkarator
subjects:
- kind: ServiceAccount
  name: kafkarator
  namespace: operators
roleRef:
  kind: ClusterRole
  name: kafkarator
  apiGroup: rbac.authorization.k8s.io